// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'PetPulse';

  @override
  String get addPet => 'Add Pet';

  @override
  String get editPet => 'Edit Pet';

  @override
  String get deletePet => 'Delete Pet';

  @override
  String get petName => 'Pet Name';

  @override
  String get species => 'Species';

  @override
  String get breed => 'Breed';

  @override
  String get birthday => 'Birthday';

  @override
  String get photo => 'Photo';

  @override
  String get notes => 'Notes';

  @override
  String get vaccinations => 'Vaccinations';

  @override
  String get medications => 'Medications';

  @override
  String get weight => 'Weight';

  @override
  String get petPassport => 'Pet Passport';

  @override
  String get markAsGiven => 'Mark as Given';

  @override
  String get dueToday => 'Due Today';

  @override
  String get expired => 'Expired';

  @override
  String expiresIn(int days) {
    return 'Expires in $days days';
  }

  @override
  String expiredDaysAgo(int days) {
    return 'Expired $days days ago';
  }

  @override
  String get addVaccination => 'Add Vaccination';

  @override
  String get editVaccination => 'Edit Vaccination';

  @override
  String get addMedication => 'Add Medication';

  @override
  String get editMedication => 'Edit Medication';

  @override
  String get logWeight => 'Log Weight';

  @override
  String get export => 'Export';

  @override
  String get share => 'Share';

  @override
  String get settings => 'Settings';

  @override
  String get save => 'Save';

  @override
  String get cancel => 'Cancel';

  @override
  String get delete => 'Delete';

  @override
  String get confirm => 'Confirm';

  @override
  String get overview => 'Overview';

  @override
  String get vaccinationName => 'Vaccination Name';

  @override
  String get dateAdministered => 'Date Administered';

  @override
  String get expirationDate => 'Expiration Date';

  @override
  String get vetName => 'Vet Name';

  @override
  String get medicationName => 'Medication Name';

  @override
  String get dosage => 'Dosage';

  @override
  String get frequency => 'Frequency';

  @override
  String get startDate => 'Start Date';

  @override
  String get endDate => 'End Date';

  @override
  String get daily => 'Daily';

  @override
  String get weekly => 'Weekly';

  @override
  String get monthly => 'Monthly';

  @override
  String get weightKg => 'Weight (kg)';

  @override
  String get date => 'Date';

  @override
  String get noPets => 'No pets yet. Add your first pet!';

  @override
  String get noVaccinations => 'No vaccinations recorded.';

  @override
  String get noMedications => 'No medications recorded.';

  @override
  String get noWeightEntries => 'No weight entries yet.';

  @override
  String deleteConfirmTitle(String name) {
    return 'Delete $name?';
  }

  @override
  String get deleteConfirmMessage => 'This action cannot be undone.';

  @override
  String get premium => 'Premium';

  @override
  String get upgradeToPremium => 'Upgrade to Premium';

  @override
  String get premiumDescription =>
      'Unlimited pets, PDF passport export, medication reminders';

  @override
  String get premiumPrice => '\$14.99 one-time';

  @override
  String get restorePurchases => 'Restore Purchases';

  @override
  String get purchaseSuccess => 'Purchase successful!';

  @override
  String get purchaseError => 'Purchase failed. Please try again.';

  @override
  String get freeTierLimit =>
      'Free tier allows 1 pet. Upgrade to Premium for unlimited pets.';

  @override
  String get premiumFeature => 'This is a Premium feature.';

  @override
  String get weightTrend => 'Weight Trend';

  @override
  String get generatePassport => 'Generate Passport';

  @override
  String get sharePassport => 'Share Passport';

  @override
  String get printPassport => 'Print Passport';

  @override
  String get petInformation => 'Pet Information';

  @override
  String get currentMedications => 'Current Medications';

  @override
  String get latestWeight => 'Latest Weight';

  @override
  String get generatedBy => 'Generated by PetPulse';

  @override
  String get dog => 'Dog';

  @override
  String get cat => 'Cat';

  @override
  String get bird => 'Bird';

  @override
  String get rabbit => 'Rabbit';

  @override
  String get other => 'Other';

  @override
  String get selectSpecies => 'Select Species';

  @override
  String get selectDate => 'Select Date';

  @override
  String get selectFrequency => 'Select Frequency';

  @override
  String get fieldRequired => 'This field is required';

  @override
  String get age => 'Age';

  @override
  String years(int count) {
    return '$count years';
  }

  @override
  String months(int count) {
    return '$count months';
  }

  @override
  String get weightUnit => 'kg';

  @override
  String get medicationReminder => 'Medication Reminder';

  @override
  String medicationReminderBody(String petName, String medicationName) {
    return 'Time to give $petName their $medicationName';
  }

  @override
  String get vaccinationExpiring => 'Vaccination Expiring';

  @override
  String vaccinationExpiringBody(
    String petName,
    String vaccinationName,
    int days,
  ) {
    return '$petName\'s $vaccinationName expires in $days days';
  }

  @override
  String vaccinationExpiredBody(String petName, String vaccinationName) {
    return '$petName\'s $vaccinationName has expired!';
  }

  @override
  String get markedAsGiven => 'Marked as given';

  @override
  String get allPets => 'All Pets';

  @override
  String get tapToAdd => 'Tap + to add your first pet';

  @override
  String get choosePhoto => 'Choose Photo';

  @override
  String get takePhoto => 'Take Photo';

  @override
  String get removePhoto => 'Remove Photo';

  @override
  String get aboutApp => 'About PetPulse';

  @override
  String get aboutDescription =>
      'PetPulse helps you keep track of your pet\'s health records, vaccinations, and medications all in one place.';

  @override
  String get version => 'Version';

  @override
  String get publisher => 'Heldig Lab';

  @override
  String get microchipId => 'Microchip ID';

  @override
  String get dueMedications => 'Due Medications';

  @override
  String get upcomingVaccinations => 'Upcoming Vaccinations';

  @override
  String get freeMedicationLimit =>
      'Free tier allows 3 medications. Upgrade to Premium for unlimited.';

  @override
  String get weightLbs => 'Weight (lbs)';
}
