name: petpulse_app
description: PetPulse - Digital pet passport and health tracker.
publish_to: 'none'
version: 1.0.10+10

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  in_app_purchase: ^3.2.1
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.3
  share_plus: ^10.1.3
  intl: any
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

flutter_native_splash:
  color: "#E11D48"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
