import 'dart:io';
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/medication.dart';
import '../models/pet.dart';
import '../models/vaccination.dart';
import '../models/weight_entry.dart';

class PdfService {
  PdfService._();
  static final PdfService instance = PdfService._();

  /// Generate a Pet Passport PDF.
  Future<Uint8List> generatePetPassport({
    required Pet pet,
    required List<Vaccination> vaccinations,
    required List<Medication> medications,
    WeightEntry? latestWeight,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('MMM d, yyyy');

    // Load pet photo if available
    pw.ImageProvider? petImage;
    if (pet.photoPath != null && pet.photoPath!.isNotEmpty) {
      try {
        final file = File(pet.photoPath!);
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          petImage = pw.MemoryImage(bytes);
        }
      } catch (_) {
        // Ignore photo loading errors
      }
    }

    final primaryColor = PdfColor.fromHex('#4A90D9');
    final secondaryColor = PdfColor.fromHex('#FF8C42');
    final textColor = PdfColor.fromHex('#2C3E50');
    final lightGrey = PdfColor.fromHex('#F5F0EB');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(primaryColor, secondaryColor),
        footer: (context) => _buildFooter(textColor),
        build: (context) => [
          // Pet info section
          _buildPetInfoSection(
            pet: pet,
            petImage: petImage,
            dateFormat: dateFormat,
            latestWeight: latestWeight,
            primaryColor: primaryColor,
            textColor: textColor,
            lightGrey: lightGrey,
          ),
          pw.SizedBox(height: 20),

          // Vaccinations table
          if (vaccinations.isNotEmpty)
            _buildVaccinationsSection(
              vaccinations: vaccinations,
              dateFormat: dateFormat,
              primaryColor: primaryColor,
              textColor: textColor,
              lightGrey: lightGrey,
            ),

          if (vaccinations.isNotEmpty) pw.SizedBox(height: 20),

          // Medications table
          if (medications.isNotEmpty)
            _buildMedicationsSection(
              medications: medications,
              dateFormat: dateFormat,
              primaryColor: primaryColor,
              textColor: textColor,
              lightGrey: lightGrey,
            ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(PdfColor primary, PdfColor secondary) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 10),
      decoration: pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: primary, width: 2),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Pet Passport',
            style: pw.TextStyle(
              fontSize: 28,
              fontWeight: pw.FontWeight.bold,
              color: primary,
            ),
          ),
          pw.Text(
            'PetPulse',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
              color: secondary,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(PdfColor textColor) {
    final dateFormat = DateFormat('MMM d, yyyy');
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by PetPulse on ${dateFormat.format(DateTime.now())}',
            style: pw.TextStyle(
              fontSize: 9,
              color: textColor,
            ),
          ),
          pw.Text(
            'Heldig Lab',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey500,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildPetInfoSection({
    required Pet pet,
    pw.ImageProvider? petImage,
    required DateFormat dateFormat,
    WeightEntry? latestWeight,
    required PdfColor primaryColor,
    required PdfColor textColor,
    required PdfColor lightGrey,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: lightGrey,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Photo
          if (petImage != null)
            pw.Container(
              width: 100,
              height: 100,
              margin: const pw.EdgeInsets.only(right: 16),
              decoration: pw.BoxDecoration(
                borderRadius: pw.BorderRadius.circular(8),
                image: pw.DecorationImage(
                  image: petImage,
                  fit: pw.BoxFit.cover,
                ),
              ),
            )
          else
            pw.Container(
              width: 100,
              height: 100,
              margin: const pw.EdgeInsets.only(right: 16),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey300,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Center(
                child: pw.Text(
                  _speciesEmoji(pet.species),
                  style: const pw.TextStyle(fontSize: 40),
                ),
              ),
            ),
          // Details
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  pet.name,
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: textColor,
                  ),
                ),
                pw.SizedBox(height: 6),
                _infoRow('Species', _capitalizeFirst(pet.species), textColor),
                if (pet.breed.isNotEmpty)
                  _infoRow('Breed', pet.breed, textColor),
                if (pet.birthday != null)
                  _infoRow(
                      'Birthday', dateFormat.format(pet.birthday!), textColor),
                if (pet.birthday != null)
                  _infoRow('Age', pet.ageString, textColor),
                if (pet.microchipId != null && pet.microchipId!.isNotEmpty)
                  _infoRow('Microchip ID', pet.microchipId!, textColor),
                if (latestWeight != null)
                  _infoRow('Weight',
                      '${latestWeight.weightKg.toStringAsFixed(1)} kg', textColor),
              ],
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _infoRow(String label, String value, PdfColor textColor) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 70,
            child: pw.Text(
              '$label:',
              style: pw.TextStyle(
                fontSize: 10,
                fontWeight: pw.FontWeight.bold,
                color: textColor,
              ),
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(fontSize: 10, color: textColor),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildVaccinationsSection({
    required List<Vaccination> vaccinations,
    required DateFormat dateFormat,
    required PdfColor primaryColor,
    required PdfColor textColor,
    required PdfColor lightGrey,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Vaccinations',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: primaryColor,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 10,
            color: PdfColors.white,
          ),
          headerDecoration: pw.BoxDecoration(color: primaryColor),
          cellStyle: pw.TextStyle(fontSize: 9, color: textColor),
          cellAlignments: {
            0: pw.Alignment.centerLeft,
            1: pw.Alignment.center,
            2: pw.Alignment.center,
            3: pw.Alignment.centerLeft,
          },
          headers: ['Vaccination', 'Date', 'Expires', 'Vet'],
          data: vaccinations.map((v) {
            return [
              v.name,
              dateFormat.format(v.dateAdministered),
              v.expirationDate != null
                  ? dateFormat.format(v.expirationDate!)
                  : 'N/A',
              v.vetName ?? '',
            ];
          }).toList(),
        ),
      ],
    );
  }

  pw.Widget _buildMedicationsSection({
    required List<Medication> medications,
    required DateFormat dateFormat,
    required PdfColor primaryColor,
    required PdfColor textColor,
    required PdfColor lightGrey,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Current Medications',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
            color: primaryColor,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 10,
            color: PdfColors.white,
          ),
          headerDecoration: pw.BoxDecoration(color: primaryColor),
          cellStyle: pw.TextStyle(fontSize: 9, color: textColor),
          cellAlignments: {
            0: pw.Alignment.centerLeft,
            1: pw.Alignment.center,
            2: pw.Alignment.center,
          },
          headers: ['Medication', 'Dosage', 'Frequency'],
          data: medications.map((m) {
            return [
              m.name,
              m.dosage,
              _capitalizeFirst(m.frequency),
            ];
          }).toList(),
        ),
      ],
    );
  }

  String _speciesEmoji(String species) {
    switch (species.toLowerCase()) {
      case 'dog':
        return 'D';
      case 'cat':
        return 'C';
      case 'bird':
        return 'B';
      case 'rabbit':
        return 'R';
      default:
        return 'P';
    }
  }

  String _capitalizeFirst(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}
